// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function scr_alert_word(){
	msg[0] = "Debe ingresar un nombre"
	msg[1] = "Debe ingresar un rut valido"
	msg[2] = "El rut debe ser sin puntos, sin guion ni digito verificador"
	msg[3] = "Debe ingresar un contrasena"
	msg[4] = "Debe repetir la contrasena"
	msg[5] = "Las contrasenas no coinciden"
	msg[6] = "Ingreso correcto"
	msg[7] = "Rut o contrasena incorrecta"
	msg[8] = "Debe ingresar Fecha de Nacimiento"
	msg[9] = "La fecha de nacimiento debe ser en formato DD/MM/AAAA"
	msg[10] = "Debe Ingresar una contraseña"
	msg[11] = "Rut ya registrado"
	msg[12] = "Debe ingresar un email"
	msg[13] = "Debe seleccionar sexo"
	msg[14] = "Debe seleccionar Nacionalidad"
	msg[15] = "Debe seleccionar Educación"
	msg[16] = "Debe seleccionar tipo de salud"
	msg[17] = "Debe ingresar dia"
	msg[18] = "Debe ingresar mes"
	msg[19] = "Debe ingresar ano"
	msg[20] = "Debe ingresar apellido"
}